# Generated by Django 5.2.7 on 2025-10-05 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfoliophoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dibujos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='drawings/')),
                ('palabras_clave', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
