# Generated by Django 5.2.7 on 2025-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20251006_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dibujos',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
