# Generated by Django 4.1.13 on 2025-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tecnologia_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(upload_to='proyectos/'),
        ),
    ]
