# Generated by Django 4.1.13 on 2025-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_proyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='icono',
            field=models.FileField(upload_to='iconos/'),
        ),
    ]
