# Generated by Django 4.1.13 on 2025-12-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tecnologia_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
