"""
Django settings for django-base-pro project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# Librerías para variables de entorno
import environ
import os
# Libreria para internacionalización
from django.utils.translation import gettext_lazy as _

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    ENVIRONMENT=(str, 'dev'),  # dev | production
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
SETTINGS_DIR = Path(__file__).resolve().parent
CONFIG_BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT_DIR = Path(__file__).resolve().parent.parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(SETTINGS_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'testserver', '.trycloudflare.com', 'capitanandalucia.duckdns.org', # ¡Sin http://!
    'www.capitanandalucia.duckdns.org', 'capitanandalucia.com', 'www.capitanandalucia.com', ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'axes',
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    
    "api",  # la app que crearemos
    "core", # HUB principal de la pagina web
    "portafolio",  # app del portafolio
    "tickets",  # app de tickets
    "social",
    "transfers",
    "notifications",
    "workouts",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'axes.middleware.AxesMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Es importante el orden para que las traducciones esten preparadas
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.ApiLoginRedirectMiddleware',
]

# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24  # 24 hours in seconds
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on every request
SESSION_COOKIE_HTTPONLY = True  # Security: prevent JavaScript access
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024 * 1024  # 30 GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024 * 1024  # 30 GB

# VirusTotal Configuration (optional)
VIRUSTOTAL_API_KEY = env('VIRUSTOTAL_API_KEY', default=None)

# reCAPTCHA secret (para verificar tokens en el servidor). Defínelo en .env si deseas activar CAPTCHA.
RECAPTCHA_SECRET = env('RECAPTCHA_SECRET', default=None)
# Permite activar/desactivar comprobación de reCAPTCHA desde .env.
# Por defecto se activa si hay RECAPTCHA_SECRET configurado.
RECAPTCHA_ENABLED = env.bool('RECAPTCHA_ENABLED', default=bool(RECAPTCHA_SECRET))

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Internacionalización
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': CONFIG_BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

LANGUAGES = [
    ('es', _('Spanish')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    PROJECT_ROOT_DIR / 'locale',
]

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = CONFIG_BASE_DIR / "staticfiles"

# Directorio principal de archivos estáticos
# STATICFILES_DIRS = [
#     CONFIG_BASE_DIR / "static",
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Logging configuration for development debugging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'transfers': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.JWTCookieAuthentication",
    ],
    # Throttling global para mitigar fuerza bruta y abuso
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "api.throttling.StaffUserRateThrottle",  # Throttle personalizado para staff
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "50/min",          # Reducido para probar retry (cambiar a 300 en producción)
        "user": "500/min",         # Usuarios normales: 500 peticiones/min
        "staff": "1000/min",       # Staff y superusuarios: 1000 peticiones/min
        # scopes específicos
        "login": "5/min",
        "register": "3/min",
    },
}

MEDIA_URL = '/media/'
#MEDIA_ROOT = CONFIG_BASE_DIR / 'media'


# JWT Configuration
from datetime import timedelta

# =============================================================================
# ENVIRONMENT-BASED CONFIGURATION
# =============================================================================
# La variable ENVIRONMENT controla automáticamente todas las configuraciones
# de seguridad. Valores: 'dev' (default) | 'production'
ENVIRONMENT = env('ENVIRONMENT')
IS_PRODUCTION = ENVIRONMENT == 'production'


# CONFIGURACION DE MEDIA
if IS_PRODUCTION:
    MEDIA_ROOT = '/mnt/media_storage/capiweb_media'
else:
    MEDIA_ROOT = CONFIG_BASE_DIR / 'media'

# Validación de variables críticas en producción
# Si falta alguna, Django no arrancará y mostrará un error claro
if IS_PRODUCTION:
    REQUIRED_ENV_VARS = [
        'SECRET_KEY',
        'POSTGRES_DB',
        'POSTGRES_USER', 
        'POSTGRES_PASSWORD',
        'CORS_ALLOWED_ORIGINS',
        'CSRF_TRUSTED_ORIGINS',
    ]
    missing_vars = [var for var in REQUIRED_ENV_VARS if not env(var, default=None)]
    if missing_vars:
        raise ValueError(
            f"⚠️ PRODUCCIÓN: Faltan variables de entorno críticas: {', '.join(missing_vars)}\n"
            f"Por favor, configúralas en tu archivo .env antes de ejecutar en producción."
        )

# JWT Settings - Se configuran según el entorno
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # 24 horas
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_SECURE': IS_PRODUCTION,  # True en producción, False en dev
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
}

# Security Settings - Automáticos según ENVIRONMENT
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS - Solo en producción
if IS_PRODUCTION:
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Configuración de django-axes
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # horas
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# CORS Configuration - Según ENVIRONMENT
if IS_PRODUCTION:
    # En producción, configurar tus dominios aquí
    CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
    CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
else:
    # En desarrollo, permitir localhost
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:4200",
        "http://127.0.0.1:4200",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:4200',
        'http://127.0.0.1:4200',
    ]

CORS_ALLOW_CREDENTIALS = True

# =============================================================================
# GOOGLE OAUTH 2.0 CONFIGURATION
# =============================================================================
# Las credenciales se obtienen en: https://console.cloud.google.com/apis/credentials
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default=None)
GOOGLE_CLIENT_SECRET = env('GOOGLE_CLIENT_SECRET', default=None)
GOOGLE_OAUTH_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)
