# Generated by Django 4.1.13 on 2025-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
