# Generated by Django 4.1.13 on 2025-12-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0003_folder_filetransfer_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='is_shared_copy',
            field=models.BooleanField(default=False),
        ),
    ]
