# Generated by Django 4.1.13 on 2025-12-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0007_populate_uploader_for_existing_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
