# Generated by Django 4.1.13 on 2025-12-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0008_add_thumbnail_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetransfer',
            name='is_viewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='filetransfer',
            index=models.Index(fields=['folder', 'is_viewed'], name='transfers_f_folder__901196_idx'),
        ),
        migrations.AddIndex(
            model_name='filetransfer',
            index=models.Index(fields=['owner', 'folder'], name='transfers_f_owner_i_cc0263_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='transfers_f_owner_i_659df2_idx'),
        ),
    ]
