# Generated by Django 4.1.13 on 2026-01-02 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(db_index=True, help_text='Identificador único del usuario en Google (sub claim)', max_length=255, unique=True)),
                ('google_email', models.EmailField(help_text='Email de la cuenta de Google vinculada', max_length=254)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil OAuth de Google',
                'verbose_name_plural': 'Perfiles OAuth de Google',
            },
        ),
    ]
