# Generated by Django 4.1.13 on 2026-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workouts/days/'),
        ),
    ]
