# Generated by Django 4.1.13 on 2026-01-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_routineday_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='is_active_variant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='workouts.routineexercise'),
        ),
    ]
