# Generated by Django 4.1.13 on 2026-01-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_routineexercise_is_active_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='icon',
            field=models.CharField(blank=True, default='fitness_center', max_length=50),
        ),
    ]
