# Generated by Django 4.1.13 on 2026-01-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_routineexercise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Custom name for this exercise in this routine', max_length=255),
        ),
    ]
