# Generated by Django 4.1.13 on 2026-01-16 18:00

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify
import unicodedata


def generate_slugs_for_existing_data(apps, schema_editor):
    """Generate slugs for all existing routines, days, and exercises."""
    Routine = apps.get_model('workouts', 'Routine')
    RoutineDay = apps.get_model('workouts', 'RoutineDay')
    RoutineExercise = apps.get_model('workouts', 'RoutineExercise')
    
    def create_slug(text):
        """Generate a slug from text."""
        normalized = unicodedata.normalize('NFD', text)
        ascii_text = normalized.encode('ascii', 'ignore').decode('ascii')
        return slugify(ascii_text) or 'item'
    
    def unique_slug(base_slug, existing_slugs):
        """Make sure slug is unique within a scope."""
        slug = base_slug
        counter = 1
        while slug in existing_slugs:
            slug = f"{base_slug}-{counter}"
            counter += 1
        existing_slugs.add(slug)
        return slug
    
    # Generate slugs for routines (unique per user)
    user_routine_slugs = {}  # {user_id: set of slugs}
    for routine in Routine.objects.all():
        if routine.user_id not in user_routine_slugs:
            user_routine_slugs[routine.user_id] = set()
        
        base_slug = create_slug(routine.title)
        routine.slug = unique_slug(base_slug, user_routine_slugs[routine.user_id])
        routine.save()
    
    # Generate slugs for routine days (unique per routine)
    DAY_NAMES = ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']
    routine_day_slugs = {}  # {routine_id: set of slugs}
    for day in RoutineDay.objects.all():
        if day.routine_id not in routine_day_slugs:
            routine_day_slugs[day.routine_id] = set()
        
        if day.title:
            base_slug = create_slug(day.title)
        else:
            base_slug = DAY_NAMES[day.day_of_week] if day.day_of_week < len(DAY_NAMES) else 'dia'
        day.slug = unique_slug(base_slug, routine_day_slugs[day.routine_id])
        day.save()
    
    # Generate slugs for routine exercises (globally unique)
    exercise_slugs = set()
    for exercise in RoutineExercise.objects.select_related('exercise').all():
        if exercise.custom_name:
            base_slug = create_slug(exercise.custom_name)
        elif exercise.exercise:
            base_slug = create_slug(exercise.exercise.name)
        else:
            base_slug = 'ejercicio'
        exercise.slug = unique_slug(base_slug, exercise_slugs)
        exercise.save()


def reverse_slugs(apps, schema_editor):
    """Reverse: clear all slugs."""
    Routine = apps.get_model('workouts', 'Routine')
    RoutineDay = apps.get_model('workouts', 'RoutineDay')
    RoutineExercise = apps.get_model('workouts', 'RoutineExercise')
    
    Routine.objects.update(slug='')
    RoutineDay.objects.update(slug='')
    RoutineExercise.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0005_routineexercise_custom_name'),
    ]

    operations = [
        # Step 1: Remove existing unique_together temporarily
        migrations.AlterUniqueTogether(
            name='routineday',
            unique_together={('routine', 'day_of_week')},
        ),
        
        # Step 2: Add slug fields (without unique constraint)
        migrations.AddField(
            model_name='routine',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='routineday',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        
        # Step 3: Generate slugs for existing data
        migrations.RunPython(generate_slugs_for_existing_data, reverse_slugs),
        
        # Step 4: Add unique constraints now that all slugs are populated
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('user', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='routineday',
            unique_together={('routine', 'day_of_week'), ('routine', 'slug')},
        ),
    ]
