# Generated by Django 4.1.13 on 2026-01-16 18:51

from django.db import migrations, models
import secrets
import string


# Characters for short_id (URL-safe, no confusing chars like 0/O, 1/l/I)
SHORT_ID_CHARS = string.ascii_letters + string.digits
SHORT_ID_CHARS = SHORT_ID_CHARS.replace('0', '').replace('O', '').replace('l', '').replace('I', '').replace('1', '')


def generate_short_id(length=8):
    """Generate a random URL-safe short ID."""
    return ''.join(secrets.choice(SHORT_ID_CHARS) for _ in range(length))


def generate_short_ids_for_existing_data(apps, schema_editor):
    """Populate short_id for all existing records."""
    Routine = apps.get_model('workouts', 'Routine')
    RoutineDay = apps.get_model('workouts', 'RoutineDay')
    RoutineExercise = apps.get_model('workouts', 'RoutineExercise')
    
    # Track used short_ids to ensure uniqueness across all models
    used_short_ids = set()
    
    def get_unique_short_id():
        for _ in range(100):
            short_id = generate_short_id()
            if short_id not in used_short_ids:
                used_short_ids.add(short_id)
                return short_id
        raise ValueError("Could not generate unique short_id")
    
    # Generate short_ids for Routines
    for routine in Routine.objects.all():
        if not routine.short_id:
            routine.short_id = get_unique_short_id()
            routine.save(update_fields=['short_id'])
    
    # Generate short_ids for RoutineDays
    for day in RoutineDay.objects.all():
        if not day.short_id:
            day.short_id = get_unique_short_id()
            day.save(update_fields=['short_id'])
    
    # Generate short_ids for RoutineExercises
    for exercise in RoutineExercise.objects.all():
        if not exercise.short_id:
            exercise.short_id = get_unique_short_id()
            exercise.save(update_fields=['short_id'])


def noop(apps, schema_editor):
    """Reverse migration does nothing."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_add_slugs'),
    ]

    operations = [
        # Step 1: Remove old unique constraints
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='routineday',
            unique_together={('routine', 'day_of_week')},
        ),
        # Step 2: Add short_id fields without unique constraint first
        migrations.AddField(
            model_name='routine',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, default=''),
        ),
        migrations.AddField(
            model_name='routineday',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, default=''),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, default=''),
        ),
        # Step 3: Populate short_ids for existing records
        migrations.RunPython(generate_short_ids_for_existing_data, noop),
        # Step 4: Now add unique constraint
        migrations.AlterField(
            model_name='routine',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='short_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
