# Generated by Django 4.1.13 on 2026-01-18 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0007_add_short_id_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motivational/')),
                ('description', models.TextField(help_text='Descripción opcional de la imagen')),
                ('group', models.CharField(choices=[('welcome', 'Bienvenida del Usuario'), ('daily_first', 'Primera Vez del Día'), ('routine_complete', 'Finalización de la Rutina'), ('user_return', 'Vuelta del Usuario')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar temporalmente sin eliminar')),
                ('order', models.IntegerField(default=0, help_text='Orden manual (menor primero)')),
            ],
            options={
                'ordering': ['group', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMotivationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(db_index=True, max_length=20)),
                ('last_shown_at', models.DateTimeField(auto_now=True)),
                ('shown_images_cycle', models.JSONField(default=list, help_text='IDs de imágenes mostradas en el ciclo actual')),
                ('cycle_count', models.IntegerField(default=0, help_text='Número de ciclos completados')),
                ('last_image_shown', models.ForeignKey(blank=True, help_text='Última imagen mostrada para evitar repetición inmediata', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.motivationalimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='motivationalimage',
            index=models.Index(fields=['group', 'is_active'], name='workouts_mo_group_cfe62a_idx'),
        ),
        migrations.AddIndex(
            model_name='usermotivationhistory',
            index=models.Index(fields=['user', 'group'], name='workouts_us_user_id_2ad09c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermotivationhistory',
            unique_together={('user', 'group')},
        ),
    ]
