# Generated by Django 4.1.13 on 2026-01-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_motivationalimage_usermotivationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workouts/routines/'),
        ),
    ]
