# Generated by Django 4.1.13 on 2026-01-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_add_routine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercise',
            name='is_cardio',
            field=models.BooleanField(default=False, help_text='Whether this is a cardio exercise'),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='target_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target distance in km', max_digits=6),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='target_duration_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Target duration in minutes'),
        ),
        migrations.AddField(
            model_name='routineexercise',
            name='target_resistance',
            field=models.PositiveSmallIntegerField(default=0, help_text='Resistance/force level (1-20)'),
        ),
    ]
