# Generated by Django 4.1.13 on 2026-01-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_add_cardio_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance in km for cardio', max_digits=6),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes for cardio'),
        ),
    ]
