# Generated by Django 4.1.13 on 2026-01-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_add_cardio_fields_to_exerciseset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='resistance',
            field=models.PositiveIntegerField(default=0, help_text='Resistance level for cardio'),
        ),
    ]
