# Generated by Django 4.1.13 on 2026-01-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_add_resistance_to_exerciseset'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
