# Generated by Django 4.1.13 on 2026-01-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_exercise_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='is_custom',
        ),
    ]
