# Generated by Django 4.1.13 on 2026-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_remove_exercise_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True if created by user via get_or_create, False if template'),
        ),
    ]
