# Generated by Django 4.1.13 on 2026-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_exercise_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='icon',
            field=models.CharField(blank=True, default='fitness_center', max_length=50),
        ),
    ]
